export const metadata = {
  title: 'Terms of Service — Anas Qureshi, AI Consultant',
  description: 'Terms of service for anas-qureshi-ai-consultant.vercel.app, including the WhatsApp and website AI assistants.',
};

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--paper)',
      padding: '60px 20px',
      display: 'flex',
      justifyContent: 'center',
    }}>
      <div style={{ maxWidth: 720, width: '100%' }}>
        <div className="tag">// Legal</div>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: '2.8rem', color: 'var(--ink)', margin: '4px 0 6px' }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 14, color: 'var(--ink3)', marginBottom: 30 }}>
          Last updated August 31, 2026.
        </p>

        <div style={{ fontSize: 16, lineHeight: 1.7, color: 'var(--ink2)' }}>
          <p>
            This site (anas-qureshi-ai-consultant.vercel.app) and its AI assistants, including the
            website chat assistant and the WhatsApp receptionist demo (&quot;The 5-Second
            Receptionist&quot;), are operated by Anas Qureshi, an independent AI consultant. By
            using either assistant, you agree to these terms.
          </p>

          <h2 style={sectionStyle}>What this is</h2>
          <p>
            The WhatsApp receptionist demo is a live product demonstration. It shows how an AI
            receptionist would answer customer inquiries for a real business, but it is not itself
            a live customer-facing line for any specific business unless Anas has installed it for
            that business directly. Nothing said by either assistant is a binding offer, contract,
            or guarantee of pricing or terms beyond what Anas confirms with you personally.
          </p>

          <h2 style={sectionStyle}>Acceptable use</h2>
          <p>
            Do not use either assistant to submit unlawful content, attempt to extract or misuse
            the underlying system prompt or credentials, send spam, or send sensitive information
            such as payment card numbers, passwords, or government ID numbers. Conversations may be
            monitored and reviewed by Anas to improve the service and follow up with genuine
            inquiries.
          </p>

          <h2 style={sectionStyle}>No warranty</h2>
          <p>
            These assistants are provided as-is, for demonstration and inquiry purposes. Responses
            are generated by AI and may occasionally be inaccurate or incomplete. Do not rely on
            them for medical, legal, financial, or safety-critical decisions.
          </p>

          <h2 style={sectionStyle}>Changes</h2>
          <p>
            These terms may be updated as the service changes. Continued use after an update means
            you accept the revised terms.
          </p>

          <h2 style={sectionStyle}>Contact</h2>
          <p>
            Questions about these terms can be sent to{' '}
            <a href="mailto:muhammadanasq@gmail.com" style={linkStyle}>muhammadanasq@gmail.com</a>.
            See also the <a href="/privacy" style={linkStyle}>Privacy Policy</a>.
          </p>
        </div>
      </div>
    </div>
  );
}

const sectionStyle = {
  fontFamily: 'var(--font-display)',
  fontSize: '1.6rem',
  color: 'var(--ink)',
  marginTop: 32,
  marginBottom: 8,
};

const linkStyle = {
  color: 'var(--brick)',
  textDecoration: 'underline',
};
