// THE ONLY citations the coach may use. Each was verified live for the delivered plans (Mizan/Plans/*) or is on the
// live site. Grok picks an id; the server attaches ref + text from here, so the model can never invent or misquote one.
// Copy of this file lives at supabase/functions/mizan-coach/sources.ts (run `npm run sync`). Add a source only after verifying it.
export const SOURCES = {
  q7_201: { ref: "Qur'an 7:201, The Clear Quran", use: 'the whisper that seems to come from nowhere; remembering Allah makes one see clearly (naming the trigger, a\'udhu)', text: 'Indeed, when Satan whispers to those mindful (of Allah), they remember (their Lord) then they start to see (things) clearly.' },
  q24_30: { ref: "Qur'an 24:30, The Clear Quran", use: 'lowering the gaze at the first glance, not managing it after looking on', text: '(O Prophet), tell the believing men to lower their gaze and guard their chastity. That is purer for them. Surely Allah is All-Aware of what they do.' },
  q13_28: { ref: "Qur'an 13:28, The Clear Quran", use: 'real comfort on a hard day comes from remembrance of Allah, not distraction', text: 'those who believe and whose hearts find comfort in the remembrance of Allah. Surely in the remembrance of Allah do hearts find comfort.' },
  q3_135: { ref: "Qur'an 3:135, The Clear Quran", use: 'seeking forgiveness sincerely, not going back knowingly; repentance is not permission', text: 'those who, upon committing an evil deed or wronging themselves, remember Allah and seek forgiveness for their sins—and who forgives sins except Allah?—and they do not knowingly persist in wrongdoing.' },
  q17_32: { ref: "Qur'an 17:32, The Clear Quran", use: 'do not go near it: cut the early step of the road, not only the act', text: 'Do not go near adultery. It is truly a shameful deed and an evil way.' },
  b5066: { ref: "Sahih al-Bukhari 5066, narrated by Abdullah ibn Mas'ud", use: 'marriage where able, fasting where not; pointing desire somewhere lawful', text: 'O young people, whoever among you can marry, should marry, because it helps him lower his gaze and guard his modesty, and whoever is not able to marry, should fast, as fasting diminishes his sexual power.' },
  m2766a: { ref: 'Sahih Muslim 2766a', use: 'repentance is always open; change the place/setting that makes the sin easy', text: 'Go to such and such land, for there are people there who worship Allah, worship Allah with them, and do not return to your land, for it is an evil land.' },
  b6308: { ref: "Sahih al-Bukhari 6308, the words of Abdullah ibn Mas'ud", use: 'not calling sin small or renaming it, while never despairing', text: 'A believer sees his sins as if he were sitting under a mountain afraid that it may fall upon him, whereas the depraved one considers his sins as flies passing over his nose.' },
  b7507: { ref: 'Sahih al-Bukhari 7507, Book 97, Hadith 132', use: 'Allah forgives the servant who knows he has a Lord who forgives; hope after a slip', text: 'My slave has known that he has a Lord who forgives sins and punishes for it, I therefore have forgiven my slave.' },
};

// Used only if the coach server is unreachable. Generic on purpose; the app labels these as such.
export const FALLBACK = [
  { title: 'It is not random', src: 'q7_201', step: "An urge nearly always arrives a few seconds after a feeling you did not notice: bored, tense, low, tired, or lonely.\n\nToday, every time the urge comes:\n1. Name the feeling you had just before it. Out loud if you can.\n2. Say: أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\n3. Stand up and leave the room for five minutes.\n\nTonight, note which feeling came up most." },
  { title: 'Close it the first time', src: 'q24_30', step: "The first glance is the door. Today: the instant something pulls your eyes, look away and say A'udhu billah. Do not give it a second look, and do not scroll to \"just check\".\n\nTonight, count how many times you closed it the first time." },
  { title: 'Bad night, not a bad person', src: 'q13_28', step: "A hard day looks for relief, and distraction is the wrong one. Pick your hardest hour. In it, before anything else: two rak'ahs or five minutes of dhikr, phone in another room." },
  { title: 'It was never permission', src: 'q3_135', step: "The trap is asking forgiveness and going back in the same night. If you slip today: make ghusl, seek forgiveness sincerely, and change one thing about the place or time it happened before tonight." },
  { title: 'Point the desire somewhere lawful', src: 'b5066', step: "The desire is not the enemy; where it is pointed is what matters. If you are able, fast today or tomorrow. Write down what you actually want closeness, marriage, a partner to give you." },
  { title: 'Change the place', src: 'm2766a', step: "The setting is part of the fight. Identify the one place and device where it happens most (bed, bathroom, late-night phone) and change it today: charge the phone outside the bedroom or use it only in shared rooms." },
  { title: 'Do not call it small', src: 'b6308', step: "The trick is renaming it: weekend chill, just this once. Write the name you usually give it, then write what it actually is. Fear that moves you is healthy; shame that freezes you is not. Restart, not shame." },
  { title: 'Do not go near', src: 'q17_32', step: "The road to it starts earlier than the act: the link, the follower, the video that is \"not that bad\". Find your last step before the act and cut it out today." },
  { title: 'Hope after a slip', src: 'b7507', step: "If you slipped this week, do not let it end the plan. Make ghusl, seek forgiveness, and take today's smallest step. A slip is a place to restart from, not a verdict." },
];
